twig:
  default_path: "%kernel.project_dir%/templates"
  # il faut ajouter for_themes pour avoir un bon formulaire
  form_themes:
    - "bootstrap_5_layout.html.twig"

when@test:
  twig:
    strict_variables: true
